### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/spatie/filament-markdown-editor/pull/24/commits/e80cdfaa7f67816fd0d450e6a7c02ed38d7fa07d?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/filament-markdown-editor.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "spatie/filament-markdown-editor": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by freekmurze** [comment]
@laravel-shift It seems like some of the tests fail, could you have a look?

**Comment by jasonmccreary** [comment]
@freekmurze, looks like a compatibility issue. As noted in the build failure, `filament/filament` does not yet support Laravel 11. Otherwise, the changes in this PR seem good. 👍

**Comment by mateusjunges** [comment]
Hey @freekmurze 👋 I'm trying to finish this upgrade to L11, but have some CI errors. Seems like the `<x-forms::field-wrapper> was moved to `<x-filament-forms::field-wrapper>` on v3, but when I change it the tests for v2 fails. Should we drop support for filament v2 and maybe tag a new major version? You can check the pipeline here https://github.com/mateusjunges/filament-markdown-editor/actions/runs/8308784262/job/22739390933?pr=1

**Comment by freekmurze** [comment]
> Should we drop support for filament v2 and maybe tag a new major version? You can check the failing tests here

Sounds like the way to go. Could you prepare that in this PR?

**Comment by mateusjunges** [comment]
@freekmurze I'm not sure how to prepare this work on this PR (would love to learn it if you can point me to any resource), so I opened a new one. 
#26 should be good to go

**Comment by freekmurze** [comment]
We'll handle this in #26

**Pull request closed without merging**
